================================================
 Testing the function say_my_name using doctest
================================================

# Run the test with ``python3 -m doctest -v ./tests/3-say_my_name.txt``
====================================================================

``Importing the function say_my_name``
::
    >>> say_my_name = __import__("3-say_my_name").say_my_name

``Testing the success of the function``
::
    >>> say_my_name("Olalekan", "Okewale")
    My name is Olalekan Okewale
    >>> say_my_name("Toheeb")
    My name is Toheeb 

``Testing the exception raised in the function``
::
    >>> say_my_name(23, "Smith")
    Traceback (most recent call last):
    ...
    TypeError: first_name must be a string
    >>> say_my_name("John", 78)
    Traceback (most recent call last):
    ...
    TypeError: last_name must be a string
    >>> say_my_name("Joy", None)
    Traceback (most recent call last):
    ...
    TypeError: last_name must be a string
    >>> say_my_name(None)
    Traceback (most recent call last):
    ...
    TypeError: first_name must be a string
    >>> say_my_name("Alat", False)
    Traceback (most recent call last):
    ...
    TypeError: last_name must be a string
    >>> say_my_name(True)
    Traceback (most recent call last):
    ...
    TypeError: first_name must be a string
    >>> say_my_name([2, 3], "GSD")
    Traceback (most recent call last):
    ...
    TypeError: first_name must be a string
    >>> say_my_name("Oyee", ("Smith", "John"))
    Traceback (most recent call last):
    ...
    TypeError: last_name must be a string
